#!/usr/bin/env bash

set -euo pipefail

pattern='cmd-'
result=$(git grep --no-color --line-number --fixed-strings -e "$pattern" -- \
  'assets/keymaps/' \
  ':(exclude)assets/keymaps/storybook.jsonc' \
  ':(exclude)assets/keymaps/default-macos.jsonc' \
  ':(exclude)assets/keymaps/macos/*.jsonc' || true)

if [[ -n "${result}" ]]; then
  echo "${result}"
  echo "Error: Found 'cmd-' in non-macOS keymap files."
  exit 1
fi

pattern='super-|win-|fn-'
result=$(git grep --no-color --line-number --fixed-strings -e "$pattern" -- \
  'assets/keymaps/' || true)

if [[ -n "${result}" ]]; then
  echo "${result}"
  echo "Error: Found 'super-', 'win-', or 'fn-' in keymap files. Currently these aren't used."
  exit 1
fi
