#!/bin/bash
set -eux
version="$1"

bundle_target() {
  arch="$1"
  target="$arch-apple-darwin"
  cargo clean
  ./script/bundle-mac $target
  cp target/$target/release/Gram-$arch.dmg ../gram-$version/Gram-$arch-$version.dmg
  cp target/$target/release/remote_server ../gram-$version/gram-remote_server-macos-$arch-$version
  gzip ../gram-$version/gram-remote_server-macos-$arch-$version
}

[ -d ../gram-$version ] || {
  echo "../gram-$version does not exist" >&2
  exit 1
}
bundle_target aarch64
bundle_target x86_64
